name: compile

on: [push, pull_request]

env:
  VERSION: 1.0.1
  OUTPUT_NAME: rpotool

jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          - macos-latest
          - windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile and package
      run: |
        make

        mkdir output

        if [ "${{ matrix.os }}" != "windows-latest" ]; then
          chmod +x ${{ env.OUTPUT_NAME }}
          mv ${{ env.OUTPUT_NAME }} output/
        else
          mv ${{ env.OUTPUT_NAME }}.exe output/
        fi

        mv README.md output/

    - name: Upload artifact Ubuntu
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}-${{ env.VERSION }}-linux-x64
        path: ./output

    - name: Upload artifact macOS x64
      if: matrix.os == 'macos-13'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}-${{ env.VERSION }}-macos-x64
        path: ./output

    - name: Upload artifact macOS ARM64
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}-${{ env.VERSION }}-macos-arm64
        path: ./output

    - name: Upload artifact Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}-${{ env.VERSION }}-win-x64
        path: ./output
