name: compile

on: [push, pull_request]

env:
  VERSION: 1.0.1
  FILE_PATH: src/*.c
  OUTPUT_NAME: rpotool

jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          - macos-latest
          - windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile and package
      run: |
        gcc -o ${{ env.OUTPUT_NAME }} ${{ env.FILE_PATH }} -lz -lcurl
        chmod +x ${{ env.OUTPUT_NAME }}
        mkdir output
        mv ${{ env.OUTPUT_NAME }} output/
        mv README.md output/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}-${{ env.VERSION }}-${{ matrix.os }}
        path: ./output
